name: Build with CMake

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: microsoft/setup-cmake@v3

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build with CMake
        run: cmake --build build --config Release

      - name: Archive Build Artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: Release Build
          path: build/Release/*
